name: Alerta Discord

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar alerta para Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"🚀 Novo evento no repositório: ${{ github.repository }} \n📌 Evento: ${{ github.event_name }} \n👤 Autor: ${{ github.actor }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
